version: "3.9"
services:
  mongo:
    image: "mongo:latest"
    ports: 
      - "27017:27017"
  trades-graphql-apollo-server: 
    environment:
      - mongoHost=mongo
    build: ./../trades-graphql-apollo-server
    ports: 
      - "4000:4000"
  